# Project: Day1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Day1.o areaofcircle.o
LINKOBJ  = Day1.o areaofcircle.o
LIBS     = -L"D:/SoftwareLib/Dev-Cpp/MinGW64/lib" -L"D:/SoftwareLib/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/SoftwareLib/Dev-Cpp/MinGW64/include" -I"D:/SoftwareLib/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/SoftwareLib/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/SoftwareLib/Dev-Cpp/MinGW64/include" -I"D:/SoftwareLib/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/SoftwareLib/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/SoftwareLib/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Day1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Day1.o: Day1.c
	$(CC) -c Day1.c -o Day1.o $(CFLAGS)

areaofcircle.o: areaofcircle.c
	$(CC) -c areaofcircle.c -o areaofcircle.o $(CFLAGS)
